#!/usr/bin/env python3
"""
check-copy.py — copy gate for pushingpeak.app.

This repo sits outside the iOS app's CI, so nothing else checks what the site
says. Two failure modes are caught here:

  1. BANNED TERMS. The committed term list the app's own gate reads
     (AthleteTracker/Resources/SUBMISSION-BANNED-TERMS.md). Weight framing,
     under-13 framing, entitlement vocabulary, org-purchase vocabulary.

  2. CLAIM SURFACE. Language that describes a capability the shipping app does
     not have. Today that means meet-day / competition fueling: the engine's
     `.heat` event type has zero semantics, meets are processed as generic
     practices, and the swimmer path cannot even produce `.heat`. PROJECT.md:62
     and MILESTONES.md:24 both say do not claim it in copy. Rebuild is
     Backlog 999.9.

     Denying the capability is fine and deliberate. `/why/` says "we are not
     going to pretend an app has solved them" on purpose, so the check reports
     claim-surface matches for a human to read rather than failing on them.

Only rendered text is scanned. Style blocks, script blocks and HTML comments are
stripped first, so engineering notes can name the constraint without tripping it.

Usage:
    python3 scripts/check-copy.py [--terms PATH] [paths...]

Exit codes:  0 clean · 1 banned term found · 2 term list missing or empty
"""

import argparse
import html
import os
import re
import sys

# Snapshot of the mechanically enforced terms, taken from
# AthleteTracker/Resources/SUBMISSION-BANNED-TERMS.md, re-synced 2026-09-04.
# Used when the app repo is not on this machine. Pass --terms to read the
# real file instead, which is always the source of truth.
VENDORED_TERMS = [
    r"\bseats?\b", r"\binvoice\b", r"\bpurchase order\b", r"\bper-athlete\b",
    r"\bbilled\b", r"\bsubscription price\b", r"\bunlock(s|ed|ing)?\b",
    r"\bactivate\b", r"\blicense\b", r"\bredeem your code\b",
    r"\bweight loss\b", r"\blose weight\b", r"\bfat loss\b", r"\bdiet\b",
    r"\bdieting\b", r"\bcalorie deficit\b", r"\bslim\b",
    r"\bkid\b", r"\bkids\b", r"\byouth\b", r"\bchild\b", r"\bchildren\b",
    r"\boptimal meet day\b", r"\bmeet day nutrition\b",
    # NOT r"\bperformance max\b". The real list moved it to ### Watch: it is a
    # legitimate feature name, banned only inside a claim sentence, and a neutral
    # UI or table label is fine. This snapshot banned it mechanically and produced
    # a false failure on /sources/, where it labels a mode in a table. Re-snapshot
    # from the real file rather than editing this list by hand where possible.
]

# Capabilities that do not ship. Reported, not failed: see the note above.
CLAIM_SURFACE = [
    r"\bmeet day\b", r"\bmeet-day\b", r"\brace day\b", r"\bcompetition day\b",
    r"\bheats?\b", r"\btaper\b",
    # xp_enabled is false live; describing it is a Guideline 2.3 exposure
    r"\blevel up\b", r"\bbadges?\b", r"\bXP\b",
    # none at launch
    r"\bfree trial\b",
]


def parse_terms(path):
    """Read the `- `-prefixed bullets under each `### Terms` heading.

    Mirrors the app gate's parser convention. Bullets under `### Watch` are
    judgment guidance and are deliberately not mechanical.
    """
    terms, in_terms = [], False
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            s = line.strip()
            if s.startswith("###"):
                in_terms = s.lower().startswith("### terms")
                continue
            if in_terms and s.startswith("- "):
                terms.append(s[2:].strip())
    return terms


def visible_text(src):
    """Rendered text only: drop comments, style and script, then tags."""
    s = re.sub(r"<!--.*?-->", " ", src, flags=re.S)
    s = re.sub(r"<(style|script)[^>]*>.*?</\1>", " ", s, flags=re.S | re.I)
    s = html.unescape(re.sub(r"<[^>]+>", " ", s))
    return re.sub(r"\s+", " ", s).strip()


def scan(text, patterns):
    out = []
    for p in patterns:
        for m in re.finditer(p, text, re.I):
            lo, hi = max(0, m.start() - 50), m.end() + 50
            out.append((p, m.group(0), text[lo:hi].strip()))
    return out


# /privacy/, /terms/ and /support/ are legal and review-evidence pages, not
# marketing copy, and they are REQUIRED to use vocabulary this list bans:
# "children under 13" is COPPA language, "license" is the content grant, "diet"
# appears in the medical disclaimer. They are also generated by
# publish-legal.py from the app repo, so they are not ours to reword. Scanning
# them by default produces noise that trains everyone to ignore the gate.
# Pass --include-legal to scan them anyway.
LEGAL_DIRS = {"privacy", "terms", "support"}


def find_pages(paths, include_legal=False):
    pages = []
    for p in paths:
        if os.path.isfile(p):
            pages.append(p)
            continue
        for root, dirs, files in os.walk(p):
            dirs[:] = [d for d in dirs if d not in {".git", "scripts", "fonts", "img"}]
            if not include_legal:
                dirs[:] = [d for d in dirs if d not in LEGAL_DIRS]
            pages += [os.path.join(root, f) for f in files if f.endswith(".html")]
    return sorted(set(pages))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="*", default=["."])
    ap.add_argument("--terms", help="path to SUBMISSION-BANNED-TERMS.md")
    ap.add_argument("--include-legal", action="store_true",
                    help="also scan /privacy/, /terms/ and /support/ (excluded by default; "
                         "they are generated legal pages that must use this vocabulary)")
    args = ap.parse_args()

    if args.terms:
        if not os.path.exists(args.terms):
            print(f"FAIL: term list not found at {args.terms}", file=sys.stderr)
            return 2
        terms = parse_terms(args.terms)
        source = args.terms
    else:
        terms, source = VENDORED_TERMS, "vendored snapshot (2026-08-17)"

    # A gate reading an empty list is worse than no gate.
    if not terms:
        print("FAIL: term list parsed to zero terms", file=sys.stderr)
        return 2

    pages = find_pages(args.paths or ["."], args.include_legal)
    if not pages:
        print("FAIL: no HTML pages found", file=sys.stderr)
        return 2

    print(f"Terms: {len(terms)} from {source}")
    scope = "all pages" if args.include_legal else "marketing pages (legal pages excluded)"
    print(f"Pages: {len(pages)}  [{scope}]\n")

    banned_total, claim_total = 0, 0
    for page in pages:
        with open(page, encoding="utf-8") as fh:
            text = visible_text(fh.read())
        banned = scan(text, terms)
        claims = scan(text, CLAIM_SURFACE)
        banned_total += len(banned)
        claim_total += len(claims)

        status = "FAIL" if banned else "ok"
        print(f"[{status}] {page}  ({len(text.split())} words)")
        for _, hit, ctx in banned:
            print(f"        BANNED {hit!r}: ...{ctx}...")
        for _, hit, ctx in claims:
            print(f"        review {hit!r}: ...{ctx}...")

    print()
    if banned_total:
        print(f"FAILED: {banned_total} banned term(s) in rendered copy.")
        return 1
    if claim_total:
        print(f"Clean on banned terms. {claim_total} claim-surface mention(s) "
              f"above are for a human to confirm are denials, not claims.")
    else:
        print("Clean. No banned terms, no unshipped-capability claims.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
